name = "lexnusa-web"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lexnusa-db"
database_id = "ce7f4f7e-a37c-4ef5-97c9-0b7540114982"
migrations_dir = "../../migrations"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "lexnusa-vectors"

[vars]
NEXT_PUBLIC_BASE_URL = ""
